### ISSUE TITLE
Unable to launch on Linux Mint 21.3 Cinnamon

### ISSUE THREAD

**Issue by Schlagbul** [RyanLandDev/DFSchematics#13]
When attempting to launch the .jar file through:
`java -jar DFSchematics-1.5.1.jar`
I am met with the following error:
`com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @163cc7b8'
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:245)
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:262)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:286)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:160)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:661)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:681)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:198)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	... 1 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:274)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:286)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:160)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:661)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:681)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:198)
	at java.base/java.lang.Thread.run(Thread.java:840)
`
And nothing happens, it simply prints the error and exits, no response from any sort of window.
I am on Linux Mint 21.3 with Cinnamon, my version of Java is, according to `java --version`:
`openjdk 17.0.12 2024-07-16
OpenJDK Runtime Environment (build 17.0.12+7-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 17.0.12+7-Ubuntu-1ubuntu222.04, mixed mode, sharing)
`

**Comment by Schlagbul** [comment]
Edit: Found a solution, though not my favorite, I had to download the project's source and compile it using maven.
